# Generated by Django 2.2 on 2019-05-30 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0002_medico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='idade',
            field=models.IntegerField(),
        ),
    ]
